<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pharmacie;

class PharmacieSeeder extends Seeder
{
    /**
     * Seeder pour créer des pharmacies avec leurs coordonnées GPS
     * dans différents quartiers de Ouagadougou
     */
    public function run(): void
    {
        $pharmacies = [
            [
                'nom' => 'Pharmacie Centrale',
                'adresse' => 'Avenue Kwame Nkrumah',
                'ville' => 'Ouagadougou',
                'quartier' => 'Centre-ville',
                'telephone' => '+226 25 30 11 22',
                'email' => 'contact@pharmacie-centrale.bf',
                'latitude' => 12.3714277,
                'longitude' => -1.5196603,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '20:00:00',
                'jours_ouverture' => 'Lundi - Dimanche',
                'pharmacie_garde' => true,
                'description' => 'Pharmacie de garde 24h/24, située au cœur de Ouagadougou. Large gamme de médicaments disponibles.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie du Peuple',
                'adresse' => 'Avenue de la Nation',
                'ville' => 'Ouagadougou',
                'quartier' => 'Gounghin',
                'telephone' => '+226 25 31 22 33',
                'email' => 'info@pharmacie-peuple.bf',
                'latitude' => 12.3838504,
                'longitude' => -1.5153428,
                'horaire_ouverture' => '07:30:00',
                'horaire_fermeture' => '21:00:00',
                'jours_ouverture' => 'Lundi - Samedi',
                'pharmacie_garde' => false,
                'description' => 'Pharmacie moderne avec un large choix de produits pharmaceutiques et parapharmaceutiques.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Yalgado',
                'adresse' => 'Près du CHU Yalgado',
                'ville' => 'Ouagadougou',
                'quartier' => 'Wemtenga',
                'telephone' => '+226 25 32 33 44',
                'email' => 'pharmacie.yalgado@gmail.com',
                'latitude' => 12.3925347,
                'longitude' => -1.5042806,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '19:00:00',
                'jours_ouverture' => 'Lundi - Vendredi',
                'pharmacie_garde' => false,
                'description' => 'Située à proximité du CHU Yalgado Ouédraogo. Spécialisée dans les médicaments hospitaliers.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Ouaga 2000',
                'adresse' => 'Avenue Charles de Gaulle',
                'ville' => 'Ouagadougou',
                'quartier' => 'Ouaga 2000',
                'telephone' => '+226 25 33 44 55',
                'email' => 'contact@pharmacie-ouaga2000.bf',
                'latitude' => 12.3402138,
                'longitude' => -1.4850928,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '20:00:00',
                'jours_ouverture' => 'Lundi - Dimanche',
                'pharmacie_garde' => false,
                'description' => 'Pharmacie moderne dans le quartier Ouaga 2000. Service rapide et personnel qualifié.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Tampouy',
                'adresse' => 'Route de Kaya',
                'ville' => 'Ouagadougou',
                'quartier' => 'Tampouy',
                'telephone' => '+226 25 34 55 66',
                'email' => 'pharmacie.tampouy@yahoo.fr',
                'latitude' => 12.4189891,
                'longitude' => -1.5109158,
                'horaire_ouverture' => '07:00:00',
                'horaire_fermeture' => '21:00:00',
                'jours_ouverture' => 'Lundi - Samedi',
                'pharmacie_garde' => true,
                'description' => 'Pharmacie de quartier, accueillante et à l\'écoute des patients. Prix abordables.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Patte d\'Oie',
                'adresse' => 'Carrefour Patte d\'Oie',
                'ville' => 'Ouagadougou',
                'quartier' => 'Patte d\'Oie',
                'telephone' => '+226 25 35 66 77',
                'email' => 'info@pharmacie-pattedoie.bf',
                'latitude' => 12.3998264,
                'longitude' => -1.5346017,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '19:30:00',
                'jours_ouverture' => 'Lundi - Samedi',
                'pharmacie_garde' => false,
                'description' => 'Située au carrefour Patte d\'Oie, facilement accessible. Grand parking disponible.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie de Dapoya',
                'adresse' => 'Secteur 1, Dapoya',
                'ville' => 'Ouagadougou',
                'quartier' => 'Dapoya',
                'telephone' => '+226 25 36 77 88',
                'email' => 'pharmacie.dapoya@gmail.com',
                'latitude' => 12.3544817,
                'longitude' => -1.5378861,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '20:00:00',
                'jours_ouverture' => 'Lundi - Dimanche',
                'pharmacie_garde' => false,
                'description' => 'Pharmacie de quartier avec conseil personnalisé. Livraison à domicile disponible.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Cissin',
                'adresse' => 'Route de Bobo',
                'ville' => 'Ouagadougou',
                'quartier' => 'Cissin',
                'telephone' => '+226 25 37 88 99',
                'email' => 'contact@pharmacie-cissin.bf',
                'latitude' => 12.3380556,
                'longitude' => -1.5555556,
                'horaire_ouverture' => '07:30:00',
                'horaire_fermeture' => '21:00:00',
                'jours_ouverture' => 'Lundi - Samedi',
                'pharmacie_garde' => false,
                'description' => 'Pharmacie bien équipée avec un large choix de produits. Personnel accueillant.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Zogona',
                'adresse' => 'Quartier Zogona',
                'ville' => 'Ouagadougou',
                'quartier' => 'Zogona',
                'telephone' => '+226 25 38 99 00',
                'email' => 'pharmacie.zogona@yahoo.com',
                'latitude' => 12.3455833,
                'longitude' => -1.5363889,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '19:00:00',
                'jours_ouverture' => 'Lundi - Vendredi',
                'pharmacie_garde' => false,
                'description' => 'Proche du marché de Zogona. Conseils en phytothérapie disponibles.',
                'statut' => true,
            ],
            [
                'nom' => 'Pharmacie Somgandé',
                'adresse' => 'Avenue Loudun',
                'ville' => 'Ouagadougou',
                'quartier' => 'Somgandé',
                'telephone' => '+226 25 39 00 11',
                'email' => 'info@pharmacie-somgande.bf',
                'latitude' => 12.3625000,
                'longitude' => -1.5280556,
                'horaire_ouverture' => '08:00:00',
                'horaire_fermeture' => '20:00:00',
                'jours_ouverture' => 'Lundi - Dimanche',
                'pharmacie_garde' => true,
                'description' => 'Pharmacie de garde certains weekends. Matériel médical disponible.',
                'statut' => true,
            ],
        ];

        foreach ($pharmacies as $pharmacie) {
            Pharmacie::create($pharmacie);
        }

        $this->command->info('✅ 10 pharmacies créées avec succès à Ouagadougou');
    }
}